//! Tests for lexer keyword recognition.
//! Covers control flow type and other keywords

use super::super::common;
use rl_lexer::tokentypes::TokenType;

const KEYWORDS: [(&str, TokenType); 73] = [
    ("and", TokenType::And),
    ("arr", TokenType::Array),
    ("->", TokenType::Arrow),
    ("=", TokenType::Assign),
    ("!", TokenType::Bang),
    ("!=", TokenType::BangEqual),
    ("!#", TokenType::BangHash),
    ("big", TokenType::Big),
    ("bool", TokenType::Bool),
    ("break", TokenType::Break),
    ("byte", TokenType::Byte),
    ("char", TokenType::Char),
    (":", TokenType::Colon),
    ("::", TokenType::ColonColon),
    (",", TokenType::Comma),
    ("==", TokenType::Compare),
    ("CONST", TokenType::Const),
    ("continue", TokenType::Continue),
    ("dec", TokenType::Dec),
    (".", TokenType::Dot),
    ("..", TokenType::DotDot),
    ("else", TokenType::Else),
    ("err", TokenType::Err),
    ("error", TokenType::Error),
    ("=>", TokenType::FatArrow),
    ("float", TokenType::Float),
    ("fn", TokenType::Fn),
    ("for", TokenType::For),
    ("from", TokenType::From),
    ("get", TokenType::Get),
    (">", TokenType::Greater),
    (">=", TokenType::GreaterEqual),
    ("#", TokenType::Hash),
    ("if", TokenType::If),
    ("impl", TokenType::Impl),
    ("in", TokenType::In),
    ("int", TokenType::Int),
    ("{", TokenType::LeftBrace),
    ("[", TokenType::LeftBracket),
    ("(", TokenType::LeftParen),
    ("<", TokenType::Less),
    ("<=", TokenType::LessEqual),
    ("loop", TokenType::Loop),
    ("map", TokenType::Map),
    ("match", TokenType::Match),
    ("-", TokenType::Minus),
    ("-=", TokenType::MinusEqual),
    ("\n", TokenType::Newline),
    ("null", TokenType::Null),
    ("ok", TokenType::Ok),
    ("or", TokenType::Or),
    ("+", TokenType::Plus),
    ("+=", TokenType::PlusEqual),
    ("?", TokenType::Question),
    ("record", TokenType::Record),
    ("result", TokenType::Result),
    ("return", TokenType::Return),
    ("}", TokenType::RightBrace),
    ("]", TokenType::RightBracket),
    (")", TokenType::RightParen),
    ("sbyte", TokenType::SByte),
    (";", TokenType::Semicolon),
    ("set", TokenType::Set),
    ("/", TokenType::Slash),
    ("/=", TokenType::SlashEqual),
    ("small", TokenType::Small),
    ("*", TokenType::Star),
    ("*=", TokenType::StarEqual),
    ("string", TokenType::String),
    ("tag", TokenType::Tag),
    ("uint", TokenType::UInt),
    ("while", TokenType::While),
    ("_", TokenType::Wildcard),
];

#[test]
fn keywords() {
    for (keyword, keyword_type) in KEYWORDS {
        let tokens = common::lex(keyword);
        assert_eq!(tokens[0].token, keyword_type);
        assert_eq!(tokens[0].lexeme, keyword);
    }
}
